changesetIgnorePatterns:
  - .github/**/*
  - .yarnrc.yml

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-2.0.0-rc.36.cjs
