name: Nightly

on:
  schedule:
    # - cron: '0 2 * * *' # run at 2 AM UTC
    - cron: '*/15 * * * *'

jobs:
  changes:
    name: 'Check for changes'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Any changes today?'
        run: |
          git log --since="$(date --date=yesterday)" | grep $GITHUB_SHA

  nightly:
    name: 'Nightly release'
    runs-on: ubuntu-latest

    needs: changes
    if: ${{ needs.changes.result == 'success' }}

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.x LTS
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
          registry-url: https://npm.pkg.github.com
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Install'
        run: |
          yarn

      - name: 'Bump and publish'
        run: |
          yarn version check
          yarn version apply

          git config --global user.name 'Martin Jesper Low Madsen'
          git config --global user.email 'martinjlowm@users.noreply.github.com'

          git commit -am "v$(jq -r '.version' package.json)"
          git push origin

          echo "Publish"
          # yarn npm publish

        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
